* SQUAT
** Setup
1 SEATING/UPPER BRACHING: Seat the bar tightly throughout the lift
  - Pull a tight shelf. (Shoulder together, depressed, externally rotated)
    - Brace + Pull into bar using body + Push away + Pull just with back
  - Balance the bar. Weight roll up, externally rotated pull back
2 BRACING: Stack ribs, abs punch in stomach
3 FOOTING: Setup foot for RDL Torque. Balance over midfoot. Grab floor.
4 POSTERIOR LOADING: Slack pull hips and hams. Load the hips and hamstrings.
** Descent
Drop stomach between thighs
** Hole
PUSH HARD THROUGH THE SHELF:
  - Pull bar unto shelf
  - Lock hips and press on toe to activate quads
  - Balance the push and pull of quads and hips/hams
  - Hips rise if needed
  
  
** COMMENTS
More power out of hole
Make sure hips is supporting the weight! Not low back!
Mindful of center of balance over midfoot
Dont lose tightness as you go down
Felt Weak and using too much hips on |10x7. Try to make it more stable.
Adductor Exercise?

* BENCH
** Setup
1 Pull bar tight and pull shelf. Arch using leg drive. Chin below bar.
2 Place bar on ulna and grip pinky tight. Break the bar.
3 Breathe brace filling upper chest.
3 Lift off stable, bar away from your head
** Lift 
1 Go down slow, loading and streching the pecs (!!!PULL?)
2 PUSH
  - Stay stuck in chimney push wall and back
  - Push down your chest, with the arch making the bar go straight up.
  - Push outward, squeeze pinky, activating triceps
** COMMENTS
Losing tightness towards the end of reps. Go down slow, stretching the pecs
Instablity of wrist. Make sure weight is balanced away from you on wrist. Use wrist wraps.
Joint Stacking?

* OVERHEAD PRESS
1 Brace Upper Chest (Shoulders together, depressed, externally rotated => Opens up chest)
2 Stack ribs, breathe brace
3 Setup legs for RDL, torque outward. Use hips and hams to stabilize torso.
4 Weight on ulna bone, pinkies tight. push outward to activate triceps.
5 !!Weight directly over center of mass. When off balance (front lean, use hips to stabilize)
  - Try to use hips back and forward to help lift


Use delts, dont overarch to use chest muscles
* DEADLIFT
* PULLUP
* RDL
Weight over midfoot
Pour out pelvis
Slow descent, use quads?
Load/Resist weight as you go down
Focus on Pull of Hips and Hamstring
Hip joint to rotation, lateral tightness around the pivot
  - Torque foot outward while pulling in/abducting
** Diagrams
     ^
<----O---->
     V

   I
   I 
-O)V(O-
I  <- I ->
I  <- I -> 

