* Wife
+ A wise, discerning woman... of noble character... God will prepare...

* Lion and Bears
+ Your servant has been keeping his father's sheep. When a lion or a bear came and carried off a sheep from the flock, I went afer it, struck it and rescued the sheep from its mouth. When it turned on me, I seized it by its hair, sturck it and killed it. Your servant has killed both the lion and the bear; this uncircumcised Philistine will be like on of them, because he has defied the armies of the living God. The Lord you delivered me from the paw of the bear will deliver me from the hands of this Philistine.

* The burning bush
+ There the angle of the LORD appeared to him in flames of fire from within a bush... Who am I, that I should go to Pharaoh and bring the Israelites out of Egypt? "I will be with you. And this will the sign to you that it is I who have sent you: When you have brough the people out fo Egypt, you will worship God on this mountain".... "I WILL BE WHAT I WILL BE"
+ I am nothing Lord. You are the fire that burns within me. Your will be done. Thank you for the signs and encouragements. Please help me when I am weak, comfort me. For I need you Father.

* Trust in the Lord's plan, even though you do not understand
+ Moses answered the people, “Do not be afraid. Stand firm and you will see the deliverance the Lord will bring you today. The Egyptians you see today you will never see again. The Lord will fight for you; you need only to be still.” Then the Lord said to Moses, “Why are you crying out to me? Tell the Israelites to move on. 

* Don't trust money, your strength, your ability, or your intellect
+ I had issues with the bank
+ I am humbled by my lack of strength
+ I didn't pass the qual. I am not sure of my ability
+ But I trust in God. I have faith in him to show me the way.

* I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you. (Psalm 32:8)

* Don’t urge me to leave you or to turn back from you. Where you go I will go, and where you stay I will stay. Your people will be my people and your God my God. Where you die I will die... (Ruth 1:16)
+ But Ruth replied, “Don’t urge me to leave you or to turn back from you. Where you go I will go, and where you stay I will stay. Your people will be my people and your God my God. Where you die I will die, and there I will be buried. May the LORD deal with me, be it ever so severely, if even death separates you and me.” When Naomi realized that Ruth was determined to go with her, she stopped urging her.
