* Prayer
+ partner
+ qual exams

+ 1 check or 1 month
  + how should i decide
  + dad said first monthly check
  + give with your heart
    + give all you have
  
* be fruitful and multiply. rule over the earth
+ instead of being afraid... raising up idols
+ God blessed them and said to them, “Be fruitful and increase in number; fill the earth and subdue it. Rule over the fish in the sea and the birds in the sky and over every living creature that moves on the ground. ”


* Wife
+ A wise, discerning woman... of noble character... God will prepare...

* prayer and waiting
+ pray for an answer and wait!
+ Genesis 24:12 Abraham's servant prayed God for a sign and committed to it
+ Jacob kept the matter in mind of Josephs dreams because it could be a sign from God.

* By faith
+ Hebrews 11:8 By faith abraham...

* heart
+ This is how we know what love is: Jesus Christ laid down his life for us. And we ought to lay down our lives for our brothers and sisters. If anyone has material possessions and sees a brother or sister in need but has no pity on them, how can the love of God be in that person? Dear children, let us not love with words or speech but with actions and in truth. This is how we know that we belong to the truth and how we set our hearts at rest in his presence: If our hearts condemn us, we know that God is greater than our hearts, and he knows everything. Dear friends, if our hearts do not condemn us, we have confidence before God and receive from him anything we ask, because we keep his commands and do what pleases him.

* Judging
Brothers and sisters, do not slander one another. Anyone who speaks against a brother or sister or judges them speaks against the law and judges it. When you judge the law, you are not keeping it, but sitting in judgment on it. There is only one Lawgiver and Judge, the one who is able to save and destroy. But you—who are you to judge your neighbor?

* Submit yourself to God.
+ James 4:3
+ humble yourseld before the Lord
+ Now listen, you who say, “Today or tomorrow we will go to this or that city, spend a year there, carry on business and make money.” Why, you do not even know what will happen tomorrow. What is your life? You are a mist that appears for a little while and then vanishes.
+ Instead, you ought to say, “If it is the Lord’s will, we will live and do this or that.” As it is, you boast in your arrogant schemes. All such boasting is evil. If anyone, then, knows the good they ought to do and doesn’t do it, it is sin for them

* Gideon
God asks Gideon to go and save Israel.
God understands Gideon's concerns. he tells Gideon peace. and Gideon says God is peace
Gideon says that he is too weak to do what God has asked him to do
God makes Gideon remove the idols in his lifeGod tells Gideon you have too many men I cannot deliver midian into their hands.
* Peace for afraid disciples, Doubting Simon

* you shall have no other god besides me
love the Lord your God with all your heart, soul and strength
whether you eat, drink, or do anything, do it in the name of the Lord.

* have faith
woman bleed wait for jesus
dead daughter
dont be afraid, and believe

* isiah 40
but those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not grow faint

* psalm 73
Yet I am always with you; you hold me by my right hand. You guide me with your counsel, and afterward you will take me into glory. Whom have I in heaven but you? And earth has nothing I desire besides you. My flesh and my heart may fail, but God is the strength of my heart and my portion forever. Those who are far from you will perish; you destroy all who are unfaithful to you. But as for me, it is good to be near God. I have made the Sovereign LORD my refuge; I will tell of all your deeds

* Lion and Bears
+ Your servant has been keeping his father's sheep. When a lion or a bear came and carried off a sheep from the flock, I went afer it, struck it and rescued the sheep from its mouth. When it turned on me, I seized it by its hair, sturck it and killed it. Your servant has killed both the lion and the bear; this uncircumcised Philistine will be like on of them, because he has defied the armies of the living God. The Lord you delivered me from the paw of the bear will deliver me from the hands of this Philistine.

* The burning bush
+ There the angle of the LORD appeared to him in flames of fire from within a bush... Who am I, that I should go to Pharaoh and bring the Israelites out of Egypt? "I will be with you. And this will the sign to you that it is I who have sent you: When you have brough the people out fo Egypt, you will worship God on this mountain".... "I WILL BE WHAT I WILL BE"
+ I am nothing Lord. You are the fire that burns within me. Your will be done. Thank you for the signs and encouragements. Please help me when I am weak, comfort me. For I need you Father.

* Trust in the Lord's plan, even though you do not understand
+ Moses answered the people, “Do not be afraid. Stand firm and you will see the deliverance the Lord will bring you today. The Egyptians you see today you will never see again. The Lord will fight for you; you need only to be still.” Then the Lord said to Moses, “Why are you crying out to me? Tell the Israelites to move on. 

* Don't trust money, your strength, your ability, or your intellect
+ I had issues with the bank
+ I am humbled by my lack of strength
+ I didn't pass the qual. I am not sure of my ability
+ But I trust in God. I have faith in him to show me the way.

* I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you. (Psalm 32:8)

* Don’t urge me to leave you or to turn back from you. Where you go I will go, and where you stay I will stay. Your people will be my people and your God my God. Where you die I will die... (Ruth 1:16)
+ But Ruth replied, “Don’t urge me to leave you or to turn back from you. Where you go I will go, and where you stay I will stay. Your people will be my people and your God my God. Where you die I will die, and there I will be buried. May the LORD deal with me, be it ever so severely, if even death separates you and me.” When Naomi realized that Ruth was determined to go with her, she stopped urging her.
